### ISSUE TITLE
Adding a new dataset, the image size is inconsistent with the abdominal dataset

### ISSUE THREAD

**Issue by bent1e** [TheoEst/abdominal_registration#3]
Hello, when I tried to add a new data set for training, I found that the size of my data set was inconsistent with that of the abdominal data set. Would the size of the new data set change after resample and AntsPy? What methods are used to make it run successfully when it is inconsistent with abdominal data?

**Comment by TheoEst** [comment]
Hello, 
The script `./preprocessing/ants_warped_cohort_name.py` will resize the size of our data to a common size of `(256, 160, 192)` which is necessary to use the models

**Comment by bent1e** [comment]
What is "pseudo_seg" and does it form itself?
I made an error while running. Here is my error code and dataset path
![image](https://user-images.githubusercontent.com/50535454/195829973-377b0f06-93de-4e94-a118-7a0fdfc438fa.png)
![image](https://user-images.githubusercontent.com/50535454/195830345-1f65ff49-075f-4ba9-b76b-169e3bbf313c.png)

**Comment by TheoEst** [comment]
What command did you launch exactly ? 
The `pseudo segmentation` are obtained by predicting the segmentation on all images of the datasets using a segmentation network. 

See here : https://github.com/TheoEst/abdominal_registration#pretrain
